### PR TITLE
Fix possible lock problem

### PR DESCRIPTION
**Pull request by avbasov**

### CODE REVIEW

**Comment by bioothod** [comment]
How is it possible not to unlock this lock in the first place?

**Comment by avbasov** [comment]
If "delta_T" equals 0

**Comment by bioothod** [comment]
If it is zero, then this whole code will explode and panic. I believe it could be better to fix that up instead?

**Comment by avbasov** [comment]
Well, I fixed that.
I try to solve the problem from this topic https://groups.google.com/forum/?fromgroups=#!topic/reverbrain/olyuOtoQPc0 . I've run into it too.

**Comment by bioothod** [comment]
Does it mean that pain will grow extremely large just because there were multiple updates at the same moment and not because of actual performance degradation?

What about following diff:

```
diff --git a/elliptics/stat.go b/elliptics/stat.go
index bac4525..aac33e8 100644
--- a/elliptics/stat.go
+++ b/elliptics/stat.go
@@ -245,27 +245,28 @@ func (backend *StatBackend) PIDPain() float64 {
 func (backend *StatBackend) PIDUpdate(e float64) {
    p := &backend.PID
    p.Lock()
+   defer p.Unlock()

    delta_T := time.Since(p.ErrorTime).Seconds()
-   integral_new := e*delta_T + p.IntegralError
-   diff := (e - p.Error) / delta_T
+   if delta_T == 0 {
+       integral_new := e*delta_T + p.IntegralError
+       diff := (e - p.Error) / delta_T
+
+       u := e*PIDKe + integral_new*PIDKi + diff*PIDKd
+       if u <= 0 {
+           // negative 'force' means we have to decrease/to hold down current attempts
+           // to achieve desired performance, but we do not have engine to tune its power,
+           // instead we have to select the fastest backend
+           // thus, let's just reduce the pain of the current backend when its performance
+           // is higher than desired one
+           u = p.Pain/2.0 + 1.0
+       }

-   u := e*PIDKe + integral_new*PIDKi + diff*PIDKd
-   if u <= 0 {
-       // negative 'force' means we have to decrease/to hold down current attempts
-       // to achieve desired performance, but we do not have engine to tune its power,
-       // instead we have to select the fastest backend
-       // thus, let's just reduce the pain of the current backend when its performance
-       // is higher than desired one
-       u = p.Pain/2.0 + 1.0
+       p.IntegralError = integral_new
+       p.Error = e
+       p.ErrorTime = time.Now()
+       p.Pain = u
    }
-
-   p.IntegralError = integral_new
-   p.Error = e
-   p.ErrorTime = time.Now()
-   p.Pain = u
-
-   p.Unlock()
 }

 func (sb *StatBackend) Len() int {
```

**Comment by avbasov** [comment]
Sorry, I see now. Commit was corrected. I prefer to exit immediately if nothing to do.

**Comment by bioothod** [comment]
Merged, thank you

**Pull request merged**
